---
name: softr-vibe-code-block
description: Write code for Softr Vibe Coding blocks - React/JSX components (or HTML for simple visuals) that go inside the Vibe Coding block's Content > Code tab. Use this skill whenever asked to write, fix, improve, or extend a Softr Vibe Coding block, build a React component for Softr, write JSX for a Softr block, work with @/lib/datasource hooks (useRecordCreate, useLinkedRecords, useUpload, q.select), use shadcn UI components inside Softr (Button, Badge, Select, Input, Textarea, etc.), build a custom dashboard or tool in Softr that connects to the Softr Database, or improve a vibe-generated block that's been saved to GitHub. Trigger on phrases like "write a vibe code block," "build me a vibe block for Softr," "improve this vibe block," "fix my Softr React component," "save credits and write the vibe code yourself," "this vibe block is broken," "make this vibe block look better," or any mention of @/components/ui, useRecordCreate, useLinkedRecords, q.select, or a Softr Vibe Coding block. This skill is for Vibe Coding blocks specifically (React/JSX) - for raw HTML/CSS/JS Custom Code blocks, use the softr-custom-code-block skill instead.
---

# Softr Vibe Coding Block Skill

## What this skill covers

Writing or editing the code that goes inside a Softr Vibe Coding block's **Content > Code** tab. This is React/JSX in most cases, sometimes plain HTML/CSS/JS for simple visual blocks with no data.

**For Custom Code blocks (raw HTML/CSS/JS, not React), use the `softr-custom-code-block` skill instead.**

---

## What a Vibe Coding block is

A Softr block where the code is generated by Softr's AI from a prompt. The output is a React component that lives in the Content > Code tab. Bev maintains these blocks in two ways:

1. **Write from scratch** — Bev wants Claude Code to write the complete vibe block code so she doesn't burn Softr AI credits. She then pastes the output into a fresh Vibe Coding block in Softr.
2. **Edit existing** — Softr generated something, Bev saved it to GitHub, now Claude Code edits the file in the repo to make it look better, add features, fix bugs, or fix broken vibe-generated code.

Either way, the output Claude Code writes must be **drop-in ready for the Content > Code tab**.

---

## The Vibe Coding block has five tabs

It's important to understand which tab does what, because **Claude Code only writes the Content tab**. Other tabs are configured by Bev in the Softr UI.

| Tab | What it does | Who handles it |
|-----|-------------|----------------|
| **Chat** | Softr's AI prompt interface | Bev (when she uses Softr's AI) |
| **Source** | Connects the block to a Database + Table, sets conditional filters (workspace/user filters), restricts which records the block sees | **Bev (UI only, NOT in code)** |
| **Content** | The actual JSX/HTML code for the block | **Claude Code** |
| **Actions** | Declares which fields the block uses for CRUD operations (Add Record, Update, Delete) and configures permissions | **Bev (UI), but the field aliases must match what's in code** |
| **Visibility** | Controls which user groups can see the block | Bev (UI only) |

---

## Critical constraint: filters happen in the Source tab, NOT in code

This is the single most important thing Claude Code keeps getting wrong.

**`useLinkedRecords` does not support filtering by user relationships.** There is **no way** to write code that restricts dropdowns or lists to records belonging to the logged-in user.

If Bev needs the block to only show "this user's projects" or "this account's briefs," that filtering happens in the **Source tab > Conditional Filters** in the Softr UI. Claude Code must not try to write filter logic for user-scoped data.

**What Claude Code CAN do:**
- Use `useLinkedRecords` to fetch related records (it'll respect whatever filters Bev set in the Source tab)
- Filter the returned data client-side (e.g. by name, by date) after fetching

**What Claude Code CANNOT do:**
- Write code that filters `useLinkedRecords` by user ID, account ID, or any user relationship
- Bypass the Source tab filters in code
- Make `useLinkedRecords` accept a filter parameter for user relationships

If Bev asks for user-scoped filtering and the Source tab can't handle it, the right answer is: "this needs to be set in the Source tab in Softr; here's what I'd suggest you set there" — not invent code that won't work.

---

## Two formats: JSX (default) and HTML

### JSX (React) — for anything dynamic or data-connected
This is what Softr's AI generates and what 95% of vibe blocks use. Use this format whenever the block:
- Reads from or writes to the Softr Database
- Has interactive state (forms, multi-step flows, dynamic UI)
- Uses shadcn components
- Needs hooks like `useState`, `useEffect`

### HTML/CSS/JS — for simple visual blocks with no data
For purely decorative or static visual sections (a pricing comparison, a stages diagram, a hero section), a plain HTML/CSS/JS file also works in a vibe block. Use this format when:
- There's no database interaction
- There's no React state needed
- It's visual/structural only (cards, grids, animations)
- Bev specifically asks for HTML

When in doubt, default to JSX.

---

## JSX format: file structure

Every JSX vibe block follows this shape:

```jsx
import { useState, useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { useRecordCreate, useLinkedRecords, useUpload, q } from "@/lib/datasource";
import { useCurrentUser } from "@/lib/user";
import { Check, X, ArrowRight } from "lucide-react";

// (optional) Option ID lookups for SELECT / multi-select fields
const STATUS_OPTIONS = [
  { id: "uuid-here", label: "Active" },
  { id: "uuid-here", label: "Paused" },
];

// (required if writing data) Field ID mapping
const createFields = q.select({
  name: "fieldIdHere",
  status: "fieldIdHere",
  // ...
});

// (optional) Helper functions and sub-components
function MyHelper({ ... }) { ... }

// REQUIRED: default-exported Block component is the entry point
export default function Block() {
  // hooks, state, render
  return (
    <div className="container py-10">
      ...
    </div>
  );
}
```

**Non-negotiable rules:**
1. The entry point must be a default-exported component named `Block`
2. Imports use the exact paths shown above (no `react/jsx-runtime`, no relative paths)
3. All styling uses Tailwind utility classes (no inline `style={{}}` for colours)
4. Use Tailwind **semantic tokens** (`text-primary`, `bg-muted`, `border-border`, `text-destructive`) — not raw colour classes (`text-blue-500`, `bg-gray-100`)

---

## Available imports (JSX vibe blocks)

### React
```jsx
import { useState, useRef, useEffect } from "react";
```

### shadcn UI components
```jsx
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
```
(Other shadcn components likely available — Card, Dialog, Tabs, etc. If unsure whether a specific component is available, ask Bev or stick to the ones above which are confirmed.)

### Toasts
```jsx
import { toast } from "sonner";

toast.success("Done!");
toast.error("Failed", { description: "Reason here" });
```

### Softr data layer
```jsx
import { useRecordCreate, useLinkedRecords, useUpload, q } from "@/lib/datasource";
```

### Current user
```jsx
import { useCurrentUser } from "@/lib/user";

const user = useCurrentUser();
// user.id, user.email, user.fullName
```

### Icons
```jsx
import { Check, X, ArrowRight, FileText, AlertCircle, ChevronRight, ChevronDown, ChevronUp, DownloadCloud, Video } from "lucide-react";
```

---

## The data layer: q.select and field IDs

### q.select pattern

When the block reads from or writes to a Softr Database table, every field used must be declared via `q.select({})`. Each entry maps a **readable alias** (left side, used in code) to the **actual Softr field ID** (right side).

```jsx
const createFields = q.select({
  name: "z3lpx",                  // alias "name" maps to field ID "z3lpx"
  description: "FCBU5",
  status: "wm1jM",
  projects: "yrYvH",              // linked record field
  qa_checklist: "OFoS6",          // multi-select field
});
```

### Field IDs MUST come from Bev — never invent them

This is the single most important rule for working with the database. **Claude Code must NEVER guess field IDs.** They are short random strings (5 characters, mixed case) and there's no way to derive them.

**Before writing any database-connected vibe block, Claude Code must have:**
1. The **table name** (e.g. `submissions`, `briefs`)
2. A list of **field aliases** (the readable names) and their **field IDs**
3. For SELECT or multi-select fields: the **option UUIDs** for every choice (full UUID format, e.g. `20c847f5-7a3a-4349-bc9a-d31e3b1fa6b2`)

If any of these are missing, **ask Bev for them before writing the code**. Don't write placeholder field IDs and hope for the best — the block will silently fail to write data.

A good way to ask:

> "Before I write this, I need the field IDs for the [table name] table. Can you share:
> 1. The field IDs for: [list of fields the block needs]
> 2. The option UUIDs for any SELECT or multi-select fields, with their labels
>
> You can grab field IDs from the Softr Database studio by clicking on each field."

If Bev doesn't have them to hand, suggest she gives Claude Code the existing block file from GitHub if there's a similar one — the field IDs and option UUIDs are in the constants at the top.

---

## Reading data with useLinkedRecords

```jsx
const { data: linkedProjectData } = useLinkedRecords({
  select: createFields,
  field: "projects",
  count: 100
});
const linkedProjects = linkedProjectData?.pages.flatMap((p) => p.items) ?? [];
```

- `select` — pass the same `q.select({})` object used elsewhere in the block
- `field` — the alias name of the linked record field
- `count` — how many records to fetch (default is small, set higher for dropdowns)
- The result is a paginated structure; `data.pages.flatMap((p) => p.items)` flattens it into a plain array
- Each item has `id` and `title` (the title is the primary field of the linked record)

**Reminder: any user-scoped filtering on linked records must be set in the Source tab UI, not here.**

---

## Writing data with useRecordCreate

```jsx
const createRecord = useRecordCreate({ fields: createFields });

// Check if writes are available before calling
if (!createRecord.enabled) {
  toast.error("Cannot create records right now");
  return;
}

// Build the fields object, then write
const fields = { name: "Hello", status: "uuid-here" };
try {
  await createRecord.mutateAsync(fields);
  toast.success("Created!");
} catch (e) {
  toast.error("Failed", { description: e.message });
}
```

### ⚠️ Keys MUST be aliases, not field IDs

The single most common reason a save silently 400s. The `fields` object passed to `mutate` / `mutateAsync` must be keyed by the **alias names** declared in `q.select`, NOT the underlying Softr field IDs. Softr's data layer maps alias → field ID internally; if you send field IDs as keys, every key gets stripped as unrecognised, the payload is empty, and the API returns:

```json
{ "message": "Record data cannot be empty" }
```

The Softr fetch wrapper throws away the response body, so the only error your block sees is `Failed to update record: 400` — completely invisible until you intercept `window.fetch` (see "Debugging save failures" below).

**Right** — keys are aliases:

```jsx
const select = q.select({
  memberships: "PxOWN",
  pronouns: "W933n",
});

updateRecord.mutate({
  recordId: user.id,
  fields: {
    memberships: [{ id: "rec_xyz" }],
    pronouns: { id: "uuid", label: "She" },
  },
});
```

**Wrong** — keys are field IDs (silently fails):

```jsx
updateRecord.mutate({
  recordId: user.id,
  fields: {
    PxOWN: [{ id: "rec_xyz" }],   // ❌ field ID, not alias
    W933n: { id: "uuid", label: "She" },
  },
});
```

### Field value formats

| Field type | Format | Example |
|------------|--------|---------|
| Text, long text, email, URL, phone | string | `"Hello"` |
| Number, currency, percent, rating | number | `42` |
| Checkbox | boolean | `true` |
| Date / datetime | ISO string `"YYYY-MM-DD"` | `"2026-04-13"` |
| Select (single) | `{ id, label }` object | `{ id: "20c847f5-...", label: "Beauty" }` |
| Multi-select | array of option UUIDs | `["uuid1", "uuid2"]` |
| Linked record | array of `{ id }` objects | `[{ id: "rec_abc" }]` |
| User | `user.id` from `useCurrentUser()` | `user.id` |
| Attachment | object or array of objects from `useUpload` | (see upload section) |

Note on single-selects: an earlier version of this doc said the format was a plain UUID string. That's wrong in practice — Softr expects the full `{ id, label }` object. The `bulk-import-briefs-v10.jsx` working block sends multi-selects as plain UUID arrays but single-selects need the object form.

### Debugging save failures

Softr's internal fetch wrapper around the data hooks calls `fetch`, checks `response.ok`, and throws `new Error("Failed to update record: " + response.status)` without ever calling `.text()` or `.json()` on the response body. So when you get a 400, the actual API error message is invisible to your block code.

To capture it, monkey-patch `window.fetch` while the block is mounted:

```jsx
useEffect(() => {
  const original = window.fetch;
  window.fetch = async function (...args) {
    const response = await original.apply(this, args);
    try {
      const url = typeof args[0] === "string" ? args[0] : args[0]?.url || "";
      if (url.includes("records-trigger") && !response.ok) {
        const body = await response.clone().text();
        console.error(
          "=== Softr error",
          response.status,
          response.statusText,
          "\nURL:", url,
          "\nBody:", body,
        );
      }
    } catch (e) {
      console.error("=== fetch interceptor failed:", e);
    }
    return response;
  };
  return () => { window.fetch = original; };
}, []);
```

Common error bodies and what they mean:

| Response body | Cause |
|---|---|
| `{ "message": "Record data cannot be empty" }` | You sent field IDs as keys. Switch to alias names. |
| `{ "message": "Invalid value for field 'X'" }` | Field-format mismatch. Check the type table above. |
| `{ "message": "..." }` referencing a specific UUID | Option UUID is wrong, or the option was deleted from the source table. |

Once the bug is fixed, remove the interceptor — leaving it in production wraps every fetch on the page, which is fine but unnecessary noise.

### Actions tab is auto-populated, not editable

The **Actions tab > Edit > FIELDS USED** list is generated from the aliases in `q.select`. There is no UI to add, remove, or rename fields there. The "Edit" button on that panel only controls visibility/permissions for the edit action (which user groups can perform writes), not the field list. Don't ask Bev to "add a field to the Actions tab" — she literally cannot. If a field shows up in `q.select`, it's in the Actions tab.

### Multi-select label-to-UUID lookup pattern

When mapping user input (e.g. CSV labels) to option UUIDs, build a lookup at the top of the file:

```jsx
const QA_OPTIONS = [
  { id: "20c847f5-7a3a-4349-bc9a-d31e3b1fa6b2", label: "Product visibility" },
  { id: "714e1e9d-7e02-47e5-86c8-c42da09b1ce6", label: "Product usage" },
  // ...
];

const QA_LABEL_TO_ID = {};
QA_OPTIONS.forEach((opt) => {
  QA_LABEL_TO_ID[opt.label.toLowerCase()] = opt.id;
});

// At write time, convert labels to UUIDs
function convertLabelsToIds(labelString, lookup) {
  const labels = labelString.split(";").map((s) => s.trim()).filter(Boolean);
  return labels.map((l) => lookup[l.toLowerCase()]).filter(Boolean);
}
```

### Linked records: send as `[{ id }]`

```jsx
// Match by title (or whatever primary field), then send as array of id objects
const match = linkedProjects.find((o) => o.title.toLowerCase() === inputName.toLowerCase());
if (match) {
  fields.projects = [{ id: match.id }];
}
```

### Hidden user fields

```jsx
const user = useCurrentUser();

// In the fields object:
fields.users = user?.id || null;
// For 'accounts' (or similar account fields), often best to omit and let Softr auto-assign based on logged-in user
```

Always check `user?.id` exists before writing — if it doesn't, the user isn't logged in.

### Date conversion helper

CSVs and user inputs often have non-ISO date formats. Use a helper to normalise to `YYYY-MM-DD`:

```jsx
function convertToISODate(val) {
  if (!val) return val;
  const s = val.trim();
  if (/^\d{4}-\d{2}-\d{2}/.test(s)) return s;  // already ISO
  // DD/MM/YYYY or DD-MM-YYYY or DD.MM.YYYY
  let m = s.match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})$/);
  if (m) return m[3] + "-" + m[2].padStart(2, "0") + "-" + m[1].padStart(2, "0");
  // Fallback to JS Date parsing
  const d = new Date(s);
  if (!isNaN(d.getTime())) {
    return d.getFullYear() + "-" +
      String(d.getMonth() + 1).padStart(2, "0") + "-" +
      String(d.getDate()).padStart(2, "0");
  }
  return val;  // let Softr reject it with a clear error
}
```

---

## File uploads with useUpload

```jsx
import { useUpload } from "@/lib/datasource";

const upload = useUpload();
const result = await upload.mutateAsync(file);
// result is the attachment object/array Softr expects in an attachment field
fields.video_file = result;
```

(If unsure about the exact return shape for a specific use case, ask Bev or check an existing vibe block in the repo that handles uploads.)

---

## Actions tab must match the code

The Actions tab in Softr declares which fields the block uses for CRUD operations (e.g. Add Record). The aliases used in `q.select({})` in code must correspond to fields that Bev has registered in the Actions tab.

If Claude Code adds a new field alias to `q.select({})`, it must tell Bev: "I added `field_alias_name` to the code — you'll need to add this field in the Actions tab in Softr."

---

## Styling rules

### Tailwind only, semantic tokens

Use Tailwind utility classes for all styling. Use the **semantic tokens** that adapt to Softr's theme:

| Use this | Not this |
|----------|----------|
| `text-primary` | `text-blue-500` |
| `bg-muted` | `bg-gray-100` |
| `border-border` | `border-gray-200` |
| `text-foreground` | `text-black` |
| `text-muted-foreground` | `text-gray-500` |
| `text-destructive` | `text-red-600` |
| `bg-destructive/10` | `bg-red-50` |
| `bg-card` | `bg-white` |
| `text-primary-foreground` | `text-white` |
| `ring-primary/20` | `ring-blue-200` |

The `/10`, `/20`, `/30` modifiers add transparency (e.g. `bg-primary/10` is primary colour at 10% opacity).

### Typical container

```jsx
<div className="container py-10">
  <div className="content">
    {/* block content */}
  </div>
</div>
```

### Cards, borders, radii

- Use `rounded-xl`, `rounded-2xl`, `rounded-full` for rounded corners
- `border` for default border, `border-2 border-dashed` for dashed
- `shadow-sm`, `shadow-lg`, custom shadows via Tailwind arbitrary values
- `transition-all` plus a duration class for animations

### Responsive

Use Tailwind responsive prefixes (`sm:`, `md:`, `lg:`). Vibe blocks must work on mobile — always test layout with `flex-col md:flex-row` patterns.

---

## HTML format: when to use, what it looks like

For purely visual blocks with no data, a plain HTML file works in a vibe block. The structure is a complete standalone HTML document:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Section Name</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: transparent; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    .my-container { max-width: 1400px; margin: 0 auto; padding: 20px; }
    /* ... */
  </style>
</head>
<body>
  <div class="my-container">
    <!-- content -->
  </div>
</body>
</html>
```

**Rules for HTML vibe blocks:**
- Always set `body { background: transparent; }` so it inherits the Softr page background
- Self-contained: all CSS in a `<style>` tag, all JS in a `<script>` tag
- No external React or component imports
- Safe to use Font Awesome or other CDN stylesheets via `<link>` in the head
- Animations via CSS keyframes are fine
- Responsive via media queries

When in doubt about which format Bev wants, default to JSX for anything interactive or data-connected, and HTML for pure visual sections.

---

## Common patterns

### Multi-step wizard

```jsx
export default function Block() {
  const [step, setStep] = useState(1);
  const [data, setData] = useState(null);

  return (
    <div className="container py-10">
      <div className="content">
        <h1 className="text-2xl font-bold text-foreground">My Wizard</h1>
        {step === 1 && <Step1 onNext={(d) => { setData(d); setStep(2); }} />}
        {step === 2 && <Step2 data={data} onBack={() => setStep(1)} onNext={() => setStep(3)} />}
        {step === 3 && <Step3 data={data} onBack={() => setStep(2)} />}
      </div>
    </div>
  );
}
```

### Form with validation and submit

```jsx
function MyForm() {
  const [name, setName] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const user = useCurrentUser();
  const createRecord = useRecordCreate({ fields: createFields });

  const handleSubmit = async () => {
    if (!name) { toast.error("Name is required"); return; }
    if (!user?.id) { toast.error("Please log in"); return; }
    setSubmitting(true);
    try {
      await createRecord.mutateAsync({ name, users: user.id });
      toast.success("Created!");
      setName("");
    } catch (e) {
      toast.error("Failed", { description: e.message });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="space-y-4">
      <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Name" />
      <Button onClick={handleSubmit} disabled={submitting || !createRecord.enabled}>
        {submitting ? "Saving..." : "Save"}
      </Button>
    </div>
  );
}
```

### Linked record dropdown

```jsx
const { data: projectData } = useLinkedRecords({
  select: createFields,
  field: "projects",
  count: 100
});
const projects = projectData?.pages.flatMap((p) => p.items) ?? [];

// Then in render:
<Select value={selectedId} onValueChange={setSelectedId}>
  <SelectTrigger><SelectValue placeholder="Select a project" /></SelectTrigger>
  <SelectContent>
    {projects.map((p) => (
      <SelectItem key={p.id} value={p.id}>{p.title}</SelectItem>
    ))}
  </SelectContent>
</Select>
```

### Console logging for debugging

When debugging a vibe block, prefix logs with a version marker so they're easy to find in the browser console and easy to diff against earlier versions:

```jsx
console.log("=== v3 fields:", JSON.stringify(fields));
console.log("=== v3 user:", user?.id);
```

---

## Editing existing vibe blocks (the GitHub workflow)

When Bev gives Claude Code an existing vibe block file from her repo to improve or fix:

1. **Read the whole file first** before changing anything. The constants at the top (option UUID arrays, `q.select` mapping, `DESTINATION_FIELDS`) are often the source of truth — don't break them.
2. **Preserve the field ID mapping** in `q.select({})`. Don't rename aliases unless Bev asks for it (renames cascade everywhere and break the Actions tab connection).
3. **Preserve the option UUID arrays** unless Bev says the options have changed. Even if a label looks wrong, the UUID is what Softr uses to write.
4. **Match the existing style**. If the file uses semantic Tailwind tokens, keep using them. If it uses certain helper functions (`buildFieldsFromRow`, `convertToISODate`), reuse them rather than inventing new ones.
5. **Keep the default `Block` export** — don't rename it.
6. **When in doubt about the format the block uses (JSX vs HTML), check the file extension and the imports** — `.jsx` with `import` statements = React vibe block, `.html` or `.txt` with `<!DOCTYPE html>` = plain HTML.
7. **Don't introduce new imports without confirming they exist.** If you want to use a new shadcn component, ask Bev first whether it's available in her Softr environment.

---

## Checklist before writing or editing a vibe code block

1. **Right block type?** This skill is for Vibe Coding blocks (React/JSX or HTML in the Content > Code tab). For raw Custom Code blocks, use `softr-custom-code-block`.
2. **JSX or HTML?** JSX for anything dynamic or data-connected (default). HTML only for static visual sections with no interactivity or data.
3. **Database connection?** If yes, do you have:
   - The table name?
   - All the field IDs?
   - All the option UUIDs for SELECT/multi-select fields?
   - If any are missing, **stop and ask Bev**.
4. **User-scoped filtering needed?** That goes in the Source tab UI, not in code. Tell Bev to set it there.
5. **Default export named `Block`?** It must be `export default function Block()`.
6. **Imports correct?** Using `@/components/ui/*`, `@/lib/datasource`, `@/lib/user`, `lucide-react`, `sonner` — and no others without confirming.
7. **Tailwind semantic tokens?** Using `text-primary`, `bg-muted`, etc. — not raw colours like `text-blue-500`.
8. **Field value formats correct?** Linked records as `[{ id }]`, multi-selects as arrays of UUIDs, dates as ISO strings, hidden user as `user?.id`.
9. **`createRecord.enabled` and `user?.id` checks before writing?**
10. **Error handling on async writes?** Wrap `mutateAsync` in try/catch with toast feedback.
11. **Editing existing file?** Preserved the `q.select` mapping, option UUID arrays, and default export name?
12. **New field aliases added?** Tell Bev to add them in the Actions tab.
